name: Lint

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:

    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # python -m pip --quiet install --upgrade .[lint]
        # Manually install until click v8.0.0 issue resolved
        python -m pip install pyflakes isort black
        python -m pip list

    # TODO: Update to flake8
    - name: Lint with pyflakes
      run: |
        pyflakes src

    - name: Lint with Black
      run: |
        black --check --diff --verbose .
